### PR TITLE
feat: lib package update

### PR DESCRIPTION
**Pull request by akgunberk**
[ ] - eslint gives error for constant numbers in `@hipo-base-config` ["0n"]
[ ] - storybook icon rendering plugin not working

to bypass first error for now, go to your node_modules/@hipo/eslint-config-base/common.js

replace the rule with following
```
    "no-magic-numbers": [
      "error",
      {
        ignore: [
          1,
          0,
          -1,
          // "0n"
        ]
      }
    ]
```

### CODE REVIEW

**Comment by mucahit** [comment]
@akgunberk is it ready to review? when we can finalize this

**Comment by akgunberk** [comment]
> @akgunberk is it ready to review? when we can finalize this

ready to review, we can say. we have 2 small issues i stated on description but I don't have time for this rn.
we can prioritize this if this is urgent, lets discuss ✌🏼

**Comment by yasincaliskan** [comment]
Regarding the eslint `"0n"` issue, I didn't encounter this on my local. How can I reproduce it? 🤔  @akgunberk

**Comment by jamcry** [comment]
@akgunberk what is the status of this PR? Is it working?

**Comment by akgunberk** [comment]
> @akgunberk what is the status of this PR? Is it working?

@jamcry 
it is on hold. there are two issues to be handled stated in description.
Testing also needed, it is been a while after creating this PR.

**Comment by akgunberk** [comment]
duplicated with #228

**Pull request closed without merging**
